### ISSUE TITLE
注册页面接口及站内访问权限验证

### ISSUE THREAD

**Issue by lookis** [706YouthSpace/706platform-backend#9]
需求文档及讨论：https://github.com/706YouthSpace/706platform/issues/6

**Comment by lookis** [comment]
- [x] 需要注册云片网（短信验证服务），并申请好验证码短信模板 @DouYuexi 
- [ ] 需要注册极验（人机验证服务），并申请好相关的key和secret @DouYuexi

**Comment by nomagick** [comment]
就直接用阿里的那一套呗，别开那么多需要结账的账户了

**Comment by lookis** [comment]
阿里的逻辑太复杂了，封装了一个巨大的 sdk core 包，还有很多看上去和业务一点关系都没有的参数，比方说调个短信服务居然需要我传个地域id，还有一个参数 setSysVersion 没给任何注释，直接写死 "2017-05-25"，文档也不全让直接看demo，让我怀疑阿里是不是都不准备好好搞这个服务
